// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwljiwntvshqtkmhaytn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3bGppd250dnNocXRrbWhheXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDM1MDMsImV4cCI6MjA1NzY3OTUwM30.SP5kzIouQ1RX8XcQXy-DMFFyBYv06oraAZg1hyVYeBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);